---
name: Asking a question / requesting help
about: Ask the community for help or advice
title: '[Question] '
labels: 'question'
assignees: ''

---

**Is your question related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**What specific question do you have?**
A simple, one sentence question.

**Describe solutions you've tried**
A clear and concise description of what you have tried on your own already.

**Additional context**
Add any other context or screenshots about the question.
